# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1477997927);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1477997445);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1477999170);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1477997806);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1477985015);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1477997686);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 4);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1473149930);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.migration.version", 38);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google.lastupdatetime", "1477999292227");
user_pref("browser.safebrowsing.provider.google.nextupdatetime", "1478000972227");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1477999314362");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1478002914362");
user_pref("browser.search.countryCode", "DE");
user_pref("browser.search.region", "DE");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20161025170357");
user_pref("browser.slowStartup.averageTime", 17755);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20161025170357");
user_pref("browser.startup.homepage_override.mstone", "49.0.2");
user_pref("browser.tabs.remote.autostart.2", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\",\"sync-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"pocket-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"loop-button\",\"pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"PanelUI-contents\",\"addon-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":6,\"newElementCount\":0}");
user_pref("browser.urlbar.daysBeforeHidingSuggestionsPrompt", 0);
user_pref("browser.urlbar.lastSuggestionsPromptDate", 20161031);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1473149993094");
user_pref("datareporting.sessions.current.activeTicks", 56);
user_pref("datareporting.sessions.current.firstPaint", 10555);
user_pref("datareporting.sessions.current.main", 1196);
user_pref("datareporting.sessions.current.sessionRestored", 9898);
user_pref("datareporting.sessions.current.startTime", "1477984888873");
user_pref("datareporting.sessions.current.totalTime", 6083);
user_pref("datareporting.sessions.currentIndex", 5);
user_pref("datareporting.sessions.previous.4", "{\"s\":1477910789574,\"a\":398,\"t\":74098,\"c\":true,\"m\":1539,\"fp\":54646,\"sr\":49798}");
user_pref("datareporting.sessions.prunedIndex", 3);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.lastUpdate.buildID", "20161025170357");
user_pref("dom.apps.lastUpdate.mstone", "49.0.2");
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("e10s.rollout.cohort", "disqualified-test");
user_pref("e10s.rollout.cohortSample", "0.897876");
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{\"e10srollout@mozilla.org\":{\"version\":\"1.3\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"firefox@getpocket.com\":{\"version\":\"1.0.4\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"webcompat@mozilla.org\":{\"version\":\"1.0\",\"type\":\"extension\",\"descriptor\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"multiprocessCompatible\":false,\"runInSafeMode\":true},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"49.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"49.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"runInSafeMode\":false},\"langpack-de@firefox.mozilla.org\":{\"version\":\"49.0.2\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi\",\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10s.rollout.policy", "49a");
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:49.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1477997928);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20160826.01");
user_pref("extensions.lastAppVersion", "49.0.2");
user_pref("extensions.lastPlatformVersion", "49.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{30034cc8-3324-4ff7-a632-441492c5573a}\",\"addons\":{\"asyncrendering@mozilla.org\":{\"version\":\"2.0\"}}}");
user_pref("extensions.xpiState", "{\"app-system-defaults\":{\"e10srollout@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/e10srollout@mozilla.org.xpi\",\"e\":true,\"v\":\"1.3\",\"st\":1477421042000},\"firefox@getpocket.com\":{\"d\":\"/usr/lib/firefox/browser/features/firefox@getpocket.com.xpi\",\"e\":true,\"v\":\"1.0.4\",\"st\":1477421044000},\"webcompat@mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/features/webcompat@mozilla.org.xpi\",\"e\":true,\"v\":\"1.0\",\"st\":1477421044000}},\"app-global\":{\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477423938000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477423937000},\"langpack-de@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-de@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477423932000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}.xpi\",\"e\":true,\"v\":\"49.0.2\",\"st\":1477421042000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597402000}}}");
user_pref("gecko.buildID", "20160729070702");
user_pref("gecko.mstone", "48.0");
user_pref("idle.lastDailyNotification", 1477999933);
user_pref("loop.copy.ticket", 147);
user_pref("media.gmp-gmpopenh264.abi", "x86-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1473150001);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20161025170357");
user_pref("media.gmp-manager.lastCheck", 1477984959);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1477911585);
user_pref("places.history.expiration.transient_current_max_pages", 80072);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1477911585);
user_pref("toolkit.startup.last_success", 1477984890);
user_pref("toolkit.telemetry.cachedClientID", "5f4a781e-f8d9-4271-907d-5e4df0f90c75");
user_pref("toolkit.telemetry.previousBuildID", "20161025170357");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
